services:
  #phpApache
  www:
    depends_on:
      - db
    build:
        dockerfile: ./apache-php/Dockerfile
    volumes:
      - ./TTG-SHOP/:/var/www/html
    ports:
      - 80:80
      - 443:443
  #mysql
  db:
    image: mariadb:11.3
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    command: --lower_case_table_names=1
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ttg_store_database
  
  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root

volumes:
  mysqldata:
